version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ToDoList
    environment:
      POSTGRES_DB: ToDoList
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      ports:
        -"5431:5432"
      restart: always