spring:
  application:
    name: ToDoList

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: admin

  flyway:
    enabled: true
    locations: classpath:db/migration
